apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  data_source.yml: |
    # config file version
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
  provider.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: "/etc/grafana/provisioning/dashboards"