apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prometheus
    project: anardemo
  name: prometheus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi